### ISSUE TITLE
M1 Support

### ISSUE THREAD

**Issue by tresf** [dyorgio/macos-tray-icon-fixer#5]
* :white_check_mark: x86_64 JVM: Works
* :no_entry_sign: aarch64: Crashes

Steps:

* Install OpenJDK16 for arm64 `brew install openjdk`
* Bump `pom.xml` to use `<version.jna>5.8.0</version.jna>`
* Run `BasicUsage.java` using arm64 version 

Stack trace: https://gist.github.com/tresf/b36b0fc7b2a439fefae89cb1a2df2904

**Comment by tresf** [comment]
Per @dyorgio, the crash goes away if `objc_msgSend` is [switched from varargs to explicit invocation](https://developer.apple.com/documentation/apple-silicon/addressing-architectural-differences-in-your-macos-code#Enable-Strict-Type-Enforcement-for-Dynamic-Method-Dispatching).

e.g. 

```diff
- NativeLong objc_msgSend(NativeLong receiver, Pointer selector, Object... args);
+ NativeLong objc_msgSend(NativeLong receiver, Pointer selector);
+ NativeLong objc_msgSend(NativeLong receiver, Pointer selector, byte[] bytes, int len, long encoding);
```

**Comment by dyorgio** [comment]
Hi @tresf, could you give me a feedback about last commit on a M1 hardware?

**Comment by tresf** [comment]
> Hi @tresf, could you give me a feedback about last commit on a M1 hardware?

Yes it works if #7 is also merged to update JNA to a version with `aarch64` support.

**Comment by dyorgio** [comment]
Merged! closing. 😃
